name: ASP.NET Core Web API Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x  # or the version you're using

    - name: Build and publish
      run: dotnet publish -c Release -o ./publish

    - name: Stop IIS Website
      run: |
        Import-Module WebAdministration
        Stop-WebSite -Name "practicecicdgithub" -ErrorAction SilentlyContinue

    - name: Deploy to IIS
      uses: SamKirkland/IIS-Web-App-Management@v3
      with:
        appPhysicalPath: 'D:\PublishPracticeAPIs'  # Replace with the actual physical path of your IIS website
        appSiteName: 'practicecicdgithub'  # Replace with the name of your IIS website
        package: './publish'
        iisManagementUser: 'MCNDESKTOP35.mcnsolutions.net'  # Replace with your IIS management username
        iisManagementPassword: 'Password$0011'  # Re
