name: ASP.NET Core Web API Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x  # or the version you're using
        
    - name: Create publish folder
      run: |
       mkdir ./publish
    - name: Check workspace contents
      run: |
       ls -R ${{ github.workspace }}


    - name: Build and publish
      run:  dotnet publish -c Release -o ./publish
    - name: Create zip file
      run: |
       $publishFolder = "${{ github.workspace }}/publish"
       $zipFile = "${{ github.workspace }}/publish.zip"
    
       Compress-Archive -Path $publishFolder -DestinationPath $zipFile


    - name: Stop IIS Website
      run: |
        Import-Module WebAdministration
        Stop-WebSite -Name "practicecicdgithub" -ErrorAction SilentlyContinue

    - name: Deploy to IIS
      run: |

        $publishFolder = "${{ github.workspace }}/publish"
        $siteName = "practicecicdgithub"  # Replace with your website name in IIS

        Add-WindowsFeature Web-WebServer
        Import-Module WebAdministration
        New-WebAppPool -Name "practicecicdgithub" -Force
        Set-ItemProperty "IIS:\AppPools\YourAppPoolName" -Name managedRuntimeVersion -Value ''
        New-Website -Name $siteName -Port 80 -PhysicalPath $publishFolder -ApplicationPool "practicecicdgithub"
