name: ASP.NET Core Web API Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x  # or the version you're using

    - name: Build and publish
      run: dotnet publish -c Release -o ./publish

    - name: Stop IIS Website
      run: |
        Import-Module WebAdministration
        Stop-WebSite -Name "practicecicdgithub" -ErrorAction SilentlyContinue

    - name: Deploy to IIS
      run: |
        $siteName = "practicecicdgithub"
        $sitePath = "./publish"
        Remove-Item -Recurse -Force $sitePath\*
        Copy-Item -Recurse -Force ./publish/* $sitePath
        Import-Module WebAdministration
        $pool = Get-ChildItem "IIS:\AppPools" | Where-Object { $_.Name -eq $siteName } -ErrorAction SilentlyContinue
        if ($pool -eq $null) {
          New-WebAppPool -Name $siteName
        }
        Set-ItemProperty "IIS:\AppPools\$siteName" -Name "managedRuntimeVersion" -Value ""
        $site = Get-ChildItem "IIS:\Sites" | Where-Object { $_.Name -eq $siteName } -ErrorAction SilentlyContinue
        if ($site -eq $null) {
          New-WebSite -Name $siteName -PhysicalPath $sitePath -ApplicationPool $siteName
        }
        Start-WebAppPool -Name $siteName
        Start-WebSite -Name $siteName


