# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Deploy to IIS

on:
  push:
    branches:
      - master  # Modify this if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.0

      - name: Build and publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to IIS
        uses: warrenbuckley/Deploy-IIS-App@v1.0.4
        with:
          Path: ./publish
          WebsiteName: practicecicdgithub  # Replace with the name of your IIS websit
