name: ASP.NET Core Web API Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x  # or the version you're using
        
    - name: Create publish folder
      run: |
       mkdir ./publish
    - name: Check workspace contents
      run: |
       ls -R ${{ github.workspace }}


    - name: Build and publish
      run:  dotnet publish -c Release -o ./publish
    - name: Create zip file
      run: |
       $publishFolder = "${{ github.workspace }}/publish"
       $zipFile = "${{ github.workspace }}/publish.zip"
    
       Compress-Archive -Path $publishFolder -DestinationPath $zipFile


    - name: Stop IIS Website
      run: |
        Import-Module WebAdministration
        Stop-WebSite -Name "practicecicdgithub" -ErrorAction SilentlyContinue

    - name: Deploy to IIS
      run: |
        $publishFolder = "${{ github.workspace }}/publish"
        $siteName = "practicecicdgithub"  # Replace with your website name in IIS

        # Install Web Deploy if necessary
        $webDeployUrl = "https://download.microsoft.com/download/2/2/2/22213574-A4D1-4E5F-9CDD-8D76B4370E0D/WebDeploy_amd64_en-US.msi"
        $webDeployInstaller = "$env:TEMP\WebDeploy.msi"
        Invoke-WebRequest -Uri $webDeployUrl -OutFile $webDeployInstaller
        Start-Process -Wait -FilePath msiexec -ArgumentList "/i $webDeployInstaller /qn /norestart"

        # Deploy the web application to IIS using MSDeploy
        Start-Process -Wait -FilePath "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -ArgumentList "-verb:sync -source:contentPath=$publishFolder -dest:contentPath=Default Web Site/$siteName"
