name: ASP.NET Core Web API Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x  # or the version you're using

    - name: Build and publish
      run: dotnet publish -c Release -o ./publish

    - name: Stop IIS Website
      run: |
        Import-Module WebAdministration
        Stop-WebSite -Name "practicecicdgithub" -ErrorAction SilentlyContinue

    - name: Deploy to IIS
      uses: warrenbuckley/MSDeployIISAppToAWebSite@1.0.5
      with:
        WebSiteName: 'practicecicdgithub'
        WebDeployPackage: './publish/*.zip'
        MsDeployExePath: 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
        DestinationComputerName: 'http://localhost'
        UserName: 'MCNDESKTOP35.mcnsolutions.net'
        Password: 'Password$0011'
